apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - /usr/local/bin/python3.10 scanner.py --ip 192.168.1.13
            - date; Thank you for having patience with me :)
          restartPolicy: OnFailure