apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner
            image: janavonsak/scanner:dev
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - python scanner.py --ip 192.168.1.0/24
          restartPolicy: OnFailure