apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-deployment
  labels:
    app: scanner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: scanner
        image: janavonsak/scanner:dev
        ports:
        - containerPort: 80